// Mapa curado de íconos de categoría (clave kebab-case -> componente Tabler).
// Incluye el set por defecto y opciones extra para el selector de íconos.
import {
    IconShoppingCart, IconToolsKitchen2, IconDeviceMobile, IconDeviceGamepad2,
    IconSchool, IconScissors, IconRun, IconUsers, IconBus, IconShirt, IconCar,
    IconGlassFull, IconSmoking, IconDeviceDesktop, IconPlane, IconHeartbeat,
    IconPaw, IconTool, IconHome, IconSofa, IconGift, IconHeartHandshake, IconDice,
    IconCandy, IconMoodKid, IconCarrot, IconCherry, IconCash, IconTrendingUp,
    IconPercentage, IconBuildingStore, IconCoin, IconCategory, IconWallet,
    IconCoffee, IconPizza, IconShoppingBag, IconCreditCard, IconBuildingBank,
    IconGasStation, IconBike, IconBook, IconMusic, IconMovie, IconTicket, IconPill,
    IconStethoscope, IconDog, IconCat, IconPlant, IconBriefcase, IconPigMoney,
    IconCake, IconBeer, IconBottle, IconBread, IconSalad, IconMeat, IconFish,
    IconBulb, IconWifi, IconDeviceTv, IconPhone, IconMail, IconMapPin, IconCalendar,
    IconStar, IconHeart, IconFlame, IconBallFootball, IconBarbell, IconShoe, IconReceipt,
} from '@tabler/icons-vue';

export const iconMap = {
    'shopping-cart': IconShoppingCart,
    'tools-kitchen-2': IconToolsKitchen2,
    'device-mobile': IconDeviceMobile,
    'device-gamepad-2': IconDeviceGamepad2,
    school: IconSchool,
    scissors: IconScissors,
    run: IconRun,
    users: IconUsers,
    bus: IconBus,
    shirt: IconShirt,
    car: IconCar,
    'glass-full': IconGlassFull,
    smoking: IconSmoking,
    'device-desktop': IconDeviceDesktop,
    plane: IconPlane,
    heartbeat: IconHeartbeat,
    paw: IconPaw,
    tool: IconTool,
    home: IconHome,
    sofa: IconSofa,
    gift: IconGift,
    'heart-handshake': IconHeartHandshake,
    dice: IconDice,
    candy: IconCandy,
    'mood-kid': IconMoodKid,
    carrot: IconCarrot,
    cherry: IconCherry,
    cash: IconCash,
    'trending-up': IconTrendingUp,
    percentage: IconPercentage,
    'building-store': IconBuildingStore,
    coin: IconCoin,
    category: IconCategory,
    wallet: IconWallet,
    coffee: IconCoffee,
    pizza: IconPizza,
    'shopping-bag': IconShoppingBag,
    'credit-card': IconCreditCard,
    'building-bank': IconBuildingBank,
    'gas-station': IconGasStation,
    bike: IconBike,
    book: IconBook,
    music: IconMusic,
    movie: IconMovie,
    ticket: IconTicket,
    pill: IconPill,
    stethoscope: IconStethoscope,
    dog: IconDog,
    cat: IconCat,
    plant: IconPlant,
    briefcase: IconBriefcase,
    'pig-money': IconPigMoney,
    cake: IconCake,
    beer: IconBeer,
    bottle: IconBottle,
    bread: IconBread,
    salad: IconSalad,
    meat: IconMeat,
    fish: IconFish,
    bulb: IconBulb,
    wifi: IconWifi,
    'device-tv': IconDeviceTv,
    phone: IconPhone,
    mail: IconMail,
    'map-pin': IconMapPin,
    calendar: IconCalendar,
    star: IconStar,
    heart: IconHeart,
    flame: IconFlame,
    'ball-football': IconBallFootball,
    barbell: IconBarbell,
    shoe: IconShoe,
    receipt: IconReceipt,
};

// Devuelve el componente para una clave; usa un ícono genérico si no existe.
export function resolveIcon(key) {
    return iconMap[key] || IconCategory;
}

// Claves disponibles en el selector de íconos.
export const pickerIcons = Object.keys(iconMap);
